# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de47f6a2e523d9056292b3a1276ec0783c6aeb1c740b81187e1f7b0fc5ad9ddbfba22cc77038742a1be5d3a9549b8c29b9c4f4170ade7e15e093502306717005

test:
  secret_key_base: 37709d32a5c3b01543da5498e8374802c25f76238e68c5ac3d842668da7f2f2d8f0fdd2d8d072b1eaf3af3235ca30b9e416c1c405f9191dce6186ae582b9a78d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
